[2022-08-11 11:52:49,342:  INFO: stage_01_prepare_data]:  >>>>> Stage one started
[2022-08-11 11:52:49,343:  ERROR: stage_01_prepare_data]:  name 'read_yaml' is not defined
Traceback (most recent call last):
  File "src/stage_01_prepare_data.py", line 67, in <module>
    get_data(config_path = parsed_args.config)
  File "src/stage_01_prepare_data.py", line 29, in get_data
    config = read_yaml(config_path)
NameError: name 'read_yaml' is not defined
[2022-08-11 12:02:10,860:  INFO: stage_01_prepare_data]:  >>>>> Stage one started
[2022-08-11 12:02:10,860:  ERROR: stage_01_prepare_data]:  [Errno 2] No such file or directory: 'config/config.yaml'
Traceback (most recent call last):
  File "src/stage_01_prepare_data.py", line 68, in <module>
    get_data(config_path = parsed_args.config)
  File "src/stage_01_prepare_data.py", line 30, in get_data
    config = read_yaml(config_path)
  File "/media/dev_ashish/DATA/Python37/INeuron-Classes/ML-OPS-Classes/MLFLOW-Classes/MLFLOW-Pytorch-Project/src/utils/all_utils.py", line 13, in read_yaml
    with open(path_to_yaml) as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: 'config/config.yaml'
[2022-08-11 12:02:51,383:  INFO: stage_01_prepare_data]:  >>>>> Stage one started
[2022-08-11 12:02:51,385:  INFO: all_utils]:  yaml file: configs/config.yaml loaded successfully
[2022-08-11 12:02:51,385:  INFO: stage_01_prepare_data]:  define Training kwargs
[2022-08-11 12:02:51,386:  INFO: stage_01_prepare_data]:  Updating device configurationas per cuda availability
[2022-08-11 12:02:51,418:  INFO: stage_01_prepare_data]:  transforms added
[2022-08-11 12:02:51,418:  ERROR: stage_01_prepare_data]:  local variable 'transforms' referenced before assignment
Traceback (most recent call last):
  File "src/stage_01_prepare_data.py", line 68, in <module>
    get_data(config_path = parsed_args.config)
  File "src/stage_01_prepare_data.py", line 48, in get_data
    transforms = transforms.Compose(
UnboundLocalError: local variable 'transforms' referenced before assignment
[2022-08-11 12:03:45,286:  INFO: stage_01_prepare_data]:  >>>>> Stage one started
[2022-08-11 12:03:45,288:  INFO: all_utils]:  yaml file: configs/config.yaml loaded successfully
[2022-08-11 12:03:45,288:  INFO: stage_01_prepare_data]:  define Training kwargs
[2022-08-11 12:03:45,288:  INFO: stage_01_prepare_data]:  Updating device configurationas per cuda availability
[2022-08-11 12:03:45,320:  INFO: stage_01_prepare_data]:  transforms added
[2022-08-11 12:03:45,320:  ERROR: stage_01_prepare_data]:  local variable 'transforms' referenced before assignment
Traceback (most recent call last):
  File "src/stage_01_prepare_data.py", line 68, in <module>
    get_data(config_path = parsed_args.config)
  File "src/stage_01_prepare_data.py", line 48, in get_data
    transforms = transforms.Compose(
UnboundLocalError: local variable 'transforms' referenced before assignment
[2022-08-11 12:05:00,327:  INFO: stage_01_prepare_data]:  >>>>> Stage one started
[2022-08-11 12:05:00,328:  INFO: all_utils]:  yaml file: configs/config.yaml loaded successfully
[2022-08-11 12:05:00,328:  INFO: stage_01_prepare_data]:  define Training kwargs
[2022-08-11 12:05:00,328:  INFO: stage_01_prepare_data]:  Updating device configurationas per cuda availability
[2022-08-11 12:05:00,357:  INFO: stage_01_prepare_data]:  transforms added
[2022-08-11 12:05:00,358:  INFO: stage_01_prepare_data]:  downloading training and testing data
[2022-08-11 12:05:00,547:  INFO: stage_01_prepare_data]:  defining training and testing data loader
[2022-08-11 12:05:00,551:  INFO: stage_01_prepare_data]:  Stage one completed!!! >>>>>

[2022-08-11 13:59:49,508:  INFO: stage_01_prepare_data]:  >>>>> Stage one started
[2022-08-11 13:59:49,510:  INFO: all_utils]:  yaml file: configs/config.yaml loaded successfully
[2022-08-11 13:59:49,511:  INFO: stage_01_prepare_data]:  define Training kwargs
[2022-08-11 13:59:49,511:  INFO: stage_01_prepare_data]:  Updating device configurationas per cuda availability
[2022-08-11 13:59:49,573:  INFO: stage_01_prepare_data]:  transforms added
[2022-08-11 13:59:49,574:  INFO: stage_01_prepare_data]:  downloading training and testing data
[2022-08-11 13:59:50,565:  INFO: stage_01_prepare_data]:  defining training and testing data loader
[2022-08-11 13:59:50,566:  INFO: stage_01_prepare_data]:  Stage one completed!!! >>>>>

[2022-08-11 15:23:50,068:  INFO: stage_01_prepare_data]:  >>>>> Stage one started
[2022-08-11 15:23:50,074:  INFO: all_utils]:  yaml file: configs/config.yaml loaded successfully
[2022-08-11 15:23:50,074:  INFO: stage_01_prepare_data]:  define Training kwargs
[2022-08-11 15:23:50,074:  INFO: stage_01_prepare_data]:  Updating device configurationas per cuda availability
[2022-08-11 15:23:50,128:  INFO: stage_01_prepare_data]:  transforms added
[2022-08-11 15:23:50,128:  INFO: stage_01_prepare_data]:  downloading training and testing data
[2022-08-11 15:23:50,212:  INFO: stage_01_prepare_data]:  defining training and testing data loader
[2022-08-11 15:23:50,213:  ERROR: stage_01_prepare_data]:  expected str, bytes or os.PathLike object, not dict
Traceback (most recent call last):
  File "src/stage_01_prepare_data.py", line 82, in <module>
    get_data(config_path = parsed_args.config)
  File "src/stage_01_prepare_data.py", line 61, in get_data
    model_config_filepath = os.path.join(config['artifacts'], "model_config")
  File "/media/dev_ashish/DATA1/Python37/INeuron-Classes/ML-OPS-Classes/MLFLOW-Classes/MLFLOW-Pytorch-Project/env/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not dict
[2022-08-11 15:24:41,058:  INFO: stage_01_prepare_data]:  >>>>> Stage one started
[2022-08-11 15:24:41,061:  INFO: all_utils]:  yaml file: configs/config.yaml loaded successfully
[2022-08-11 15:24:41,061:  INFO: stage_01_prepare_data]:  define Training kwargs
[2022-08-11 15:24:41,061:  INFO: stage_01_prepare_data]:  Updating device configurationas per cuda availability
[2022-08-11 15:24:41,086:  INFO: stage_01_prepare_data]:  transforms added
[2022-08-11 15:24:41,086:  INFO: stage_01_prepare_data]:  downloading training and testing data
[2022-08-11 15:24:41,136:  INFO: stage_01_prepare_data]:  defining training and testing data loader
[2022-08-11 15:24:41,137:  INFO: all_utils]:  Directory is created at artifacts/model_config
[2022-08-11 15:24:41,452:  INFO: model_utils]:  model_config is saved at artifacts/model_config/train_loader.bin
[2022-08-11 15:24:41,515:  INFO: model_utils]:  model_config is saved at artifacts/model_config/test_loader.bin
[2022-08-11 15:24:41,516:  INFO: stage_01_prepare_data]:  Stage one completed!!! >>>>>

[2022-08-11 15:32:08,743:  INFO: stage_01_prepare_data]:  >>>>> Stage one started
[2022-08-11 15:32:08,748:  INFO: all_utils]:  yaml file: configs/config.yaml loaded successfully
[2022-08-11 15:32:08,749:  INFO: stage_01_prepare_data]:  define Training kwargs
[2022-08-11 15:32:08,749:  INFO: stage_01_prepare_data]:  Updating device configurationas per cuda availability
[2022-08-11 15:32:08,799:  INFO: stage_01_prepare_data]:  transforms added
[2022-08-11 15:32:08,799:  INFO: stage_01_prepare_data]:  downloading training and testing data
[2022-08-11 15:32:08,847:  INFO: stage_01_prepare_data]:  defining training and testing data loader
[2022-08-11 15:32:08,847:  ERROR: stage_01_prepare_data]:  'model_config'
Traceback (most recent call last):
  File "src/stage_01_prepare_data.py", line 84, in <module>
    get_data(config_path = parsed_args.config)
  File "src/stage_01_prepare_data.py", line 63, in get_data
    model_config_filepath = os.path.join(artifacts['artifacts'], artifacts["model_config"])
KeyError: 'model_config'
[2022-08-11 15:32:31,817:  INFO: stage_01_prepare_data]:  >>>>> Stage one started
[2022-08-11 15:32:31,819:  INFO: all_utils]:  yaml file: configs/config.yaml loaded successfully
[2022-08-11 15:32:31,820:  INFO: stage_01_prepare_data]:  define Training kwargs
[2022-08-11 15:32:31,820:  INFO: stage_01_prepare_data]:  Updating device configurationas per cuda availability
[2022-08-11 15:32:31,870:  INFO: stage_01_prepare_data]:  transforms added
[2022-08-11 15:32:31,870:  INFO: stage_01_prepare_data]:  downloading training and testing data
[2022-08-11 15:32:31,916:  INFO: stage_01_prepare_data]:  defining training and testing data loader
[2022-08-11 15:32:31,917:  INFO: all_utils]:  Directory is created at artifacts/model_config
[2022-08-11 15:32:32,231:  INFO: model_utils]:  model_config is saved at artifacts/model_config/train_loader.bin
[2022-08-11 15:32:32,303:  INFO: model_utils]:  model_config is saved at artifacts/model_config/test_loader.bin
[2022-08-11 15:32:32,304:  INFO: stage_01_prepare_data]:  Stage one completed!!! >>>>>

[2022-08-11 15:40:58,488:  INFO: stage_02_train]:  >>>>> Stage two started
[2022-08-11 15:40:58,488:  ERROR: stage_02_train]:  [Errno 2] No such file or directory: 'config/config.yaml'
Traceback (most recent call last):
  File "src/stage_02_train.py", line 83, in <module>
    train(config_path = parsed_args.config, params_path = parsed_args.params)
  File "src/stage_02_train.py", line 48, in train
    config = read_yaml(config_path)
  File "/media/dev_ashish/DATA1/Python37/INeuron-Classes/ML-OPS-Classes/MLFLOW-Classes/MLFLOW-Pytorch-Project/src/utils/all_utils.py", line 13, in read_yaml
    with open(path_to_yaml) as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: 'config/config.yaml'
[2022-08-11 15:41:21,541:  INFO: stage_02_train]:  >>>>> Stage two started
[2022-08-11 15:41:21,541:  ERROR: stage_02_train]:  'Namespace' object has no attribute 'params'
Traceback (most recent call last):
  File "src/stage_02_train.py", line 82, in <module>
    train(config_path = parsed_args.config, params_path = parsed_args.params)
AttributeError: 'Namespace' object has no attribute 'params'
[2022-08-11 15:41:45,597:  INFO: stage_02_train]:  >>>>> Stage two started
[2022-08-11 15:41:45,597:  ERROR: stage_02_train]:  train() missing 1 required positional argument: 'params_path'
Traceback (most recent call last):
  File "src/stage_02_train.py", line 82, in <module>
    train(config_path = parsed_args.config)
TypeError: train() missing 1 required positional argument: 'params_path'
[2022-08-11 15:41:59,236:  INFO: stage_02_train]:  >>>>> Stage two started
[2022-08-11 15:41:59,242:  INFO: all_utils]:  yaml file: configs/config.yaml loaded successfully
[2022-08-11 15:41:59,282:  ERROR: stage_02_train]:  'dict' object has no attribute 'DEVICE'
Traceback (most recent call last):
  File "src/stage_02_train.py", line 81, in <module>
    train(config_path = parsed_args.config)
  File "src/stage_02_train.py", line 50, in train
    model = ConvNet().to(config.DEVICE)
AttributeError: 'dict' object has no attribute 'DEVICE'
[2022-08-11 15:44:04,390:  INFO: stage_02_train]:  >>>>> Stage two started
[2022-08-11 15:44:04,396:  INFO: all_utils]:  yaml file: configs/config.yaml loaded successfully
[2022-08-11 15:44:04,397:  INFO: stage_02_train]:  Updating device configurationas per cuda availability
[2022-08-11 15:44:08,303:  INFO: model_utils]:  model_config is loaded from artifacts/model_config/train_loader.bin
[2022-08-11 15:44:08,303:  ERROR: stage_02_train]:  'EPOCHS'
Traceback (most recent call last):
  File "src/stage_02_train.py", line 83, in <module>
    train(config_path = parsed_args.config)
  File "src/stage_02_train.py", line 70, in train
    for epoch in range(1, config['params']['EPOCHS'] + 1):
KeyError: 'EPOCHS'
[2022-08-11 15:44:37,390:  INFO: stage_02_train]:  >>>>> Stage two started
[2022-08-11 15:44:37,393:  ERROR: stage_02_train]:  while scanning a simple key
  in "configs/config.yaml", line 9, column 3
could not find expected ':'
  in "configs/config.yaml", line 11, column 1
Traceback (most recent call last):
  File "src/stage_02_train.py", line 83, in <module>
    train(config_path = parsed_args.config)
  File "src/stage_02_train.py", line 48, in train
    config = read_yaml(config_path)
  File "/media/dev_ashish/DATA1/Python37/INeuron-Classes/ML-OPS-Classes/MLFLOW-Classes/MLFLOW-Pytorch-Project/src/utils/all_utils.py", line 14, in read_yaml
    content = yaml.safe_load(yaml_file)
  File "/media/dev_ashish/DATA1/Python37/INeuron-Classes/ML-OPS-Classes/MLFLOW-Classes/MLFLOW-Pytorch-Project/env/lib/python3.7/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/media/dev_ashish/DATA1/Python37/INeuron-Classes/ML-OPS-Classes/MLFLOW-Classes/MLFLOW-Pytorch-Project/env/lib/python3.7/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/media/dev_ashish/DATA1/Python37/INeuron-Classes/ML-OPS-Classes/MLFLOW-Classes/MLFLOW-Pytorch-Project/env/lib/python3.7/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/media/dev_ashish/DATA1/Python37/INeuron-Classes/ML-OPS-Classes/MLFLOW-Classes/MLFLOW-Pytorch-Project/env/lib/python3.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/media/dev_ashish/DATA1/Python37/INeuron-Classes/ML-OPS-Classes/MLFLOW-Classes/MLFLOW-Pytorch-Project/env/lib/python3.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/media/dev_ashish/DATA1/Python37/INeuron-Classes/ML-OPS-Classes/MLFLOW-Classes/MLFLOW-Pytorch-Project/env/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/media/dev_ashish/DATA1/Python37/INeuron-Classes/ML-OPS-Classes/MLFLOW-Classes/MLFLOW-Pytorch-Project/env/lib/python3.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/media/dev_ashish/DATA1/Python37/INeuron-Classes/ML-OPS-Classes/MLFLOW-Classes/MLFLOW-Pytorch-Project/env/lib/python3.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/media/dev_ashish/DATA1/Python37/INeuron-Classes/ML-OPS-Classes/MLFLOW-Classes/MLFLOW-Pytorch-Project/env/lib/python3.7/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/media/dev_ashish/DATA1/Python37/INeuron-Classes/ML-OPS-Classes/MLFLOW-Classes/MLFLOW-Pytorch-Project/env/lib/python3.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/media/dev_ashish/DATA1/Python37/INeuron-Classes/ML-OPS-Classes/MLFLOW-Classes/MLFLOW-Pytorch-Project/env/lib/python3.7/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/media/dev_ashish/DATA1/Python37/INeuron-Classes/ML-OPS-Classes/MLFLOW-Classes/MLFLOW-Pytorch-Project/env/lib/python3.7/site-packages/yaml/scanner.py", line 115, in check_token
    while self.need_more_tokens():
  File "/media/dev_ashish/DATA1/Python37/INeuron-Classes/ML-OPS-Classes/MLFLOW-Classes/MLFLOW-Pytorch-Project/env/lib/python3.7/site-packages/yaml/scanner.py", line 152, in need_more_tokens
    self.stale_possible_simple_keys()
  File "/media/dev_ashish/DATA1/Python37/INeuron-Classes/ML-OPS-Classes/MLFLOW-Classes/MLFLOW-Pytorch-Project/env/lib/python3.7/site-packages/yaml/scanner.py", line 292, in stale_possible_simple_keys
    "could not find expected ':'", self.get_mark())
yaml.scanner.ScannerError: while scanning a simple key
  in "configs/config.yaml", line 9, column 3
could not find expected ':'
  in "configs/config.yaml", line 11, column 1
[2022-08-11 15:44:55,790:  INFO: stage_02_train]:  >>>>> Stage two started
[2022-08-11 15:44:55,792:  INFO: all_utils]:  yaml file: configs/config.yaml loaded successfully
[2022-08-11 15:44:55,792:  INFO: stage_02_train]:  Updating device configurationas per cuda availability
[2022-08-11 15:44:58,152:  INFO: model_utils]:  model_config is loaded from artifacts/model_config/train_loader.bin
[2022-08-11 15:45:00,529:  ERROR: stage_02_train]:  'dict' object has no attribute 'LOG_INTERVAL'
Traceback (most recent call last):
  File "src/stage_02_train.py", line 83, in <module>
    train(config_path = parsed_args.config)
  File "src/stage_02_train.py", line 71, in train
    train_(config, scripted_model, config['DEVICE'], train_loader, optimizer, epoch)
  File "src/stage_02_train.py", line 40, in train_
    if batch_idx % config.LOG_INTERVAL == 0:
AttributeError: 'dict' object has no attribute 'LOG_INTERVAL'
[2022-08-11 15:45:31,187:  INFO: stage_02_train]:  >>>>> Stage two started
[2022-08-11 15:45:31,190:  INFO: all_utils]:  yaml file: configs/config.yaml loaded successfully
[2022-08-11 15:45:31,191:  INFO: stage_02_train]:  Updating device configurationas per cuda availability
[2022-08-11 15:45:33,684:  INFO: model_utils]:  model_config is loaded from artifacts/model_config/train_loader.bin
[2022-08-11 15:45:34,047:  ERROR: stage_02_train]:  'LOG_INTERVAL'
Traceback (most recent call last):
  File "src/stage_02_train.py", line 83, in <module>
    train(config_path = parsed_args.config)
  File "src/stage_02_train.py", line 71, in train
    train_(config, scripted_model, config['DEVICE'], train_loader, optimizer, epoch)
  File "src/stage_02_train.py", line 40, in train_
    if batch_idx % config['LOG_INTERVAL'] == 0:
KeyError: 'LOG_INTERVAL'
[2022-08-11 15:46:10,211:  INFO: stage_02_train]:  >>>>> Stage two started
[2022-08-11 15:46:10,217:  INFO: all_utils]:  yaml file: configs/config.yaml loaded successfully
[2022-08-11 15:46:10,217:  INFO: stage_02_train]:  Updating device configurationas per cuda availability
[2022-08-11 15:46:12,650:  INFO: model_utils]:  model_config is loaded from artifacts/model_config/train_loader.bin
[2022-08-11 15:46:13,045:  ERROR: stage_02_train]:  'dict' object has no attribute 'DRY_RUN'
Traceback (most recent call last):
  File "src/stage_02_train.py", line 83, in <module>
    train(config_path = parsed_args.config)
  File "src/stage_02_train.py", line 71, in train
    train_(config, scripted_model, config['DEVICE'], train_loader, optimizer, epoch)
  File "src/stage_02_train.py", line 42, in train_
    if config.DRY_RUN:
AttributeError: 'dict' object has no attribute 'DRY_RUN'
[2022-08-11 15:46:43,884:  INFO: stage_02_train]:  >>>>> Stage two started
[2022-08-11 15:46:43,889:  INFO: all_utils]:  yaml file: configs/config.yaml loaded successfully
[2022-08-11 15:46:43,890:  INFO: stage_02_train]:  Updating device configurationas per cuda availability
[2022-08-11 15:46:46,266:  INFO: model_utils]:  model_config is loaded from artifacts/model_config/train_loader.bin
[2022-08-11 15:49:24,458:  INFO: stage_02_train]:  Stage two completed!!! >>>>>

